import os # This is the path to the directory where the PDF report will be saved
import matplotlib # This is the library used for creating the pie chart in the PDF report
matplotlib.use('Agg')  #  This is used to set the backend for matplotlib to avoid GUI issues
import matplotlib.pyplot as plt # This is the library used for creating the pie chart in the PDF report
from fpdf import FPDF # This is the library used for creating the PDF report
from datetime import datetime # This is the library used to get the current date and time

class PDF(FPDF): # This is the class that creates the PDF report, with the font and layout settings
    def header(self): # This is the header of the PDF report, with the title
        self.set_font("Arial", "B", 16)
        self.set_text_color(15, 60, 120)
        self.cell(0, 10, "GDPR Compliance Assessment Report", ln=True, align="C")
        self.ln(5)
        self.set_draw_color(15, 60, 120)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self): # This is the footer of the PDF report, with the page number and the generated by message
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(150)
        self.cell(0, 10, "Generated By Muhammad Mateen Arif's GDPR Compliance Assessment Tool", 0, 0, "C")

def generate_chart(yes_count, no_count): # This function generates a pie chart based on the compliance data
    labels = ["Compliant (Yes)", "Non-Compliant (No)"]
    sizes = [yes_count, no_count]
    colours = ["#28a745", "#dc3545"]

# Create a pie chart amd save it as an PNG file
    plt.figure(figsize=(4, 4)) 
    plt.pie(sizes, labels=labels, colors=colours, autopct='%1.1f%%', startangle=140)
    plt.axis("equal")
    chart_path = "compliance_chart.png"
    plt.savefig(chart_path, bbox_inches="tight")
    plt.close()
    return chart_path # This saves the pie chart as a PNG file

def generate_pdf(data, percentage, status): # This function generates the PDF report based on the compliance data and status
    pdf = PDF()
    pdf.add_page()
    pdf.set_font("Arial", "", 12)

    # Count yes/no rsponses
    yes_count = sum(1 for v in data.values() if v.lower() == "yes")
    no_count = sum(1 for v in data.values() if v.lower() == "no")

    # Information section
    pdf.set_text_color(0)

    # The date and time of the report generation and the name and email of the user who submitted the form
    current_datetime = datetime.now().strftime("%B %d, %Y - %I:%M:%S %p")

    pdf.cell(0, 10, f"Date & Time: {current_datetime}", ln=True)
    pdf.cell(0, 10, f"Submitted by: {data.get('name', 'N/A')} - {data.get('email', 'N/A')}", ln=True)
    pdf.ln(5)  # Space after information

    # Horizontal separator line (grey color)
    pdf.set_draw_color(169, 169, 169)  # Light grey color for the line
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())  # Line across width
    
    pdf.ln(8)  # Space after line

    # Complaince Status block with colour
    pdf.set_font("Arial", "B", 12) 
    pdf.set_fill_color(220, 220, 220)
    pdf.cell(0, 10, "Compliance Summary", ln=True, fill=True)

    if percentage >= 70:
        status_colour = (40, 167, 69)  # Green if over 70%
    elif 50 <= percentage < 70:
        status_colour = (255, 165, 0)  # Orange if between 50% and 70%
    else:
        status_colour = (220, 53, 69)  # Red if below 50%

    pdf.set_text_color(*status_colour)
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, f"Compliance Score: {percentage}%", ln=True)
    pdf.cell(0, 10, f"Status: {status}", ln=True)
    pdf.set_text_color(0)
    pdf.ln(10)

    # Add Recommendations Based on Compliance Status
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(15, 60, 120)
    pdf.cell(0, 10, "Recommendations", ln=True)
    pdf.set_text_color(0)
    pdf.set_font("Arial", "", 11)
    
    if status == "Partially Compliant":  # This is the message the user recieves when the compliance score is between 50% and 70%
         pdf.multi_cell(0, 8, "- Review areas with 'No' answers and ensure data is processed for lawful, specific purposes.\n"
                         "- Reassess your data minimisation, accuracy, and retention policies.\n"
                         "- Begin implementing technical and organisational safeguards to reduce risk.")
    elif status == "Non-Compliant":   # This is the message the user recieves when the compliance score is below 50%
        pdf.multi_cell(0, 8, "- Immediate action is highly recommended to bring your data protection practices in line with GDPR Articles 5 & 6.\n"
                         "- Consider assigning a Data Protection Officer or consulting legal experts.\n"
                         "- Develop or update your data protection policies and train relevant staff.\n"
                         "- Ensure lawful bases are documented and consent is handled properly.")
        pdf.ln(10)


    # Insert pie chart image into the PDF
    chart_path = generate_chart(yes_count, no_count)
    if os.path.exists(chart_path):
        pdf.image(chart_path, x=60, y=None, w=90)
        pdf.ln(10)

    # Grouped Answers Section
    pdf.set_fill_color(220, 220, 220)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Detailed Responses by Article", ln=True, fill=True)
    pdf.set_font("Arial", "", 11)
    pdf.ln(4)

    # Article 5 questions Title
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(15, 60, 120)
    pdf.cell(0, 10, " Article 5: Principles of Data Processing", ln=True)
    pdf.set_text_color(0)
    pdf.ln(2)

    article_5_fields = [ # This is the list of fields that are used to generate the PDF report
        "Lawfulness, fairness, and transparency",
        "Purpose limitation",
        "Data minimisation",
        "Accuracy",
        "Storage limitation",
        "Integrity and confidentiality"
    ]

    for key in article_5_fields: # 
        pdf.set_font("Arial", "B", 12)
        pdf.multi_cell(0, 8, f"{key}")
        pdf.set_font("Arial", "", 12)
        pdf.multi_cell(0, 8, f"{data.get(key, 'N/A')}")
        pdf.ln(2)

    # Article 6 questions Title
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(15, 60, 120)
    pdf.cell(0, 10, " Article 6: Lawfulness of Processing", ln=True)
    pdf.set_text_color(0)
    pdf.ln(2)

    article_6_fields = [ # This is the list of fields that are used to generate the PDF report
        "Lawful basis for processing",
        "Consent",
        "Contract necessity",
        "Legal obligation",
        "Vital interests",
        "Public task",
        "Legitimate interests"
    ]

    for key in article_6_fields: #
        pdf.set_font("Arial", "B", 12)
        pdf.multi_cell(0, 8, f"{key}")
        pdf.set_font("Arial", "", 12)
        pdf.multi_cell(0, 8, f"{data.get(key, 'N/A')}")
        pdf.ln(2)

    pdf.output("gdpr_compliance_report.pdf") # This saves the PDF report to a file called "gdpr_compliance_report.pdf"

    # Delete the chart image after saving the PDF
    if os.path.exists(chart_path):
        os.remove(chart_path)

    return "gdpr_compliance_report.pdf" # This returns the path to the PDF report
